element = {
    "t0424OutBlock":{
        "sunamt" : "추정순자산",
        "dtsunik" : "실현손익",
        "mamt" : "매입금액",
        "sunamt1" : "추정D2예수금",
        "cts_expcode" : "CTS_종목번호",
        "tappamt" : "평가금액",
        "tdtsunik" : "평가손익",
    },
    "t0424OutBlock1":{
        "expcode" : "종목번호",
        "hname" : "종목명",
        "jangb" : "잔고구분",
        "janqty" : "잔고수량",
        "mdposqt" : "매도가능수량",
        "pamt" : "평균단가",
        "mamt" : "매입금액",
        "marketgb" : "시장구분",
        "jonggb" : "종목구분",
        "janrt" : "보유비중",
        "price" : "현재가",
        "appamt" : "평가금액",
        "dtsunik" : "평가손익",
        "sunikrt" : "수익율",
        "fee" : "수수료",
        "tax" : "제세금",
        "sinamt" : "대출금액",
        "lastdt" : "만기일자",
        "msat" : "당일매수금액",
        "mpms" : "당일매수단가",
        "mdat" : "당일매도금액",
        "mpmd" : "당일매도단가",
        "jsat" : "전일매수금액",
        "jpms" : "전일매수단가",
        "jdat" : "전일매도금액",
        "jpmd" : "전일매도단가",
        "sysprocseq" : "처리순번",
        "loandt" : "대출일자",
        "sininter" : "신용이자",
    },
    "t8407OutBlock1":{
        "shcode": "종목코드",
        "hname": "종목명",
        "price": "현재가",
        "sign": "전일대비구분",
        "change": "전일대비",
        "diff": "등락율",
        "volume": "누적거래량",
        "offerho": "매도호가",
        "bidho": "매수호가",
        "cvolume": "체결수량",
        "chdegree": "체결강도",
        "open": "시가",
        "high": "고가",
        "low": "저가",
        "value": "거래대금(백만)",
        "offerrem": "우선매도잔량",
        "bidrem": "우선매수잔량",
        "totofferrem": "총매도잔량",
        "totbidrem": "총매수잔량",
        "jnilclose": "전일종가",
        "uplmtprice": "상한가",
        "dnlmtprice": "하한가",
    },
    "t3341OutBlock":{
        "cnt": "CNT",
        "idx": "IDX",
    },
    "t3341OutBlock1":{
        "rank": "순위",
        "hname": "기업명",
        "salesgrowth": "매출액증가율",
        "operatingincomegrowt": "영업이익증가율",
        "ordinaryincomegrowth": "경상이익증가율",
        "liabilitytoequity": "부채비율",
        "enterpriseratio": "유보율",
        "eps": "EPS",
        "bps": "BPS",
        "roe": "ROE",
        "shcode": "종목코드",
        "per": "PER",
        "pbr": "PBR",
        "peg": "PEG",
    },
    # 주식현재가호가조회
    "t1101OutBlock": {
        "hname": "한글명",
        "price": "현재가",
        "sign": "전일대비구분",
        "change": "전일대비",
        "diff": "등락율",
        "volume": "누적거래량",
        "jnilclose": "전일종가",
        "offerho1": "매도호가1",
        "bidho1": "매수호가1",
        "offerrem1": "매도호가수량1",
        "bidrem1": "매수호가수량1",
        "preoffercha1": "직전매도대비수량1",
        "prebidcha1": "직전매수대비수량1",
        "offerho2": "매도호가2",
        "bidho2": "매수호가2",
        "offerrem2": "매도호가수량2",
        "bidrem2": "매수호가수량2",
        "preoffercha2": "직전매도대비수량2",
        "prebidcha2": "직전매수대비수량2",
        "offerho3": "매도호가3",
        "bidho3": "매수호가3",
        "offerrem3": "매도호가수량3",
        "bidrem3": "매수호가수량3",
        "preoffercha3": "직전매도대비수량3",
        "prebidcha3": "직전매수대비수량3",
        "offerho4": "매도호가4",
        "bidho4": "매수호가4",
        "offerrem4": "매도호가수량4",
        "bidrem4": "매수호가수량4",
        "preoffercha4": "직전매도대비수량4",
        "prebidcha4": "직전매수대비수량4",
        "offerho5": "매도호가5",
        "bidho5": "매수호가5",
        "offerrem5": "매도호가수량5",
        "bidrem5": "매수호가수량5",
        "preoffercha5": "직전매도대비수량5",
        "prebidcha5": "직전매수대비수량5",
        "offerho6": "매도호가6",
        "bidho6": "매수호가6",
        "offerrem6": "매도호가수량6",
        "bidrem6": "매수호가수량6",
        "preoffercha6": "직전매도대비수량6",
        "prebidcha6": "직전매수대비수량6",
        "offerho7": "매도호가7",
        "bidho7": "매수호가7",
        "offerrem7": "매도호가수량7",
        "bidrem7": "매수호가수량7",
        "preoffercha7": "직전매도대비수량7",
        "prebidcha7": "직전매수대비수량7",
        "offerho8": "매도호가8",
        "bidho8": "매수호가8",
        "offerrem8": "매도호가수량8",
        "bidrem8": "매수호가수량8",
        "preoffercha8": "직전매도대비수량8",
        "prebidcha8": "직전매수대비수량8",
        "offerho9": "매도호가9",
        "bidho9": "매수호가9",
        "offerrem9": "매도호가수량9",
        "bidrem9": "매수호가수량9",
        "preoffercha9": "직전매도대비수량9",
        "prebidcha9": "직전매수대비수량9",
        "offerho10": "매도호가10",
        "bidho10": "매수호가10",
        "offerrem10": "매도호가수량10",
        "bidrem10": "매수호가수량10",
        "preoffercha10": "직전매도대비수량10",
        "prebidcha10": "직전매수대비수량10",
        "offer": "매도호가수량합",
        "bid": "매수호가수량합",
        "preoffercha": "직전매도대비수량합",
        "prebidcha": "직전매수대비수량합",
        "hotime": "수신시간",
        "yeprice": "예상체결가격",
        "yevolume": "예상체결수량",
        "yesign": "예상체결전일구분",
        "yechange": "예상체결전일대비",
        "yediff": "예상체결등락율",
        "tmoffer": "시간외매도잔량",
        "tmbid": "시간외매수잔량",
        "ho_status": "동시구분",
        "shcode": "단축코드",
        "uplmtprice": "상한가",
        "dnlmtprice": "하한가",
        "open": "시가",
        "high": "고가",
        "low": "저가",
    },

    # KOSPI호가잔량
    "H1_": {
        "shcode": "단축코드",
        "hotime": "호가시간",
        "offerho1": "매도호가1",
        "bidho1": "매수호가1",
        "offerrem1": "매도호가잔량1",
        "bidrem1": "매수호가잔량1",
        "offerho2": "매도호가2",
        "bidho2": "매수호가2",
        "offerrem2": "매도호가잔량2",
        "bidrem2": "매수호가잔량2",
        "offerho3": "매도호가3",
        "bidho3": "매수호가3",
        "offerrem3": "매도호가잔량3",
        "bidrem3": "매수호가잔량3",
        "offerho4": "매도호가4",
        "bidho4": "매수호가4",
        "offerrem4": "매도호가잔량4",
        "bidrem4": "매수호가잔량4",
        "offerho5": "매도호가5",
        "bidho5": "매수호가5",
        "offerrem5": "매도호가잔량5",
        "bidrem5": "매수호가잔량5",
        "offerho6": "매도호가6",
        "bidho6": "매수호가6",
        "offerrem6": "매도호가잔량6",
        "bidrem6": "매수호가잔량6",
        "offerho7": "매도호가7",
        "bidho7": "매수호가7",
        "offerrem7": "매도호가잔량7",
        "bidrem7": "매수호가잔량7",
        "offerho8": "매도호가8",
        "bidho8": "매수호가8",
        "offerrem8": "매도호가잔량8",
        "bidrem8": "매수호가잔량8",
        "offerho9": "매도호가9",
        "bidho9": "매수호가9",
        "offerrem9": "매도호가잔량9",
        "bidrem9": "매수호가잔량9",
        "offerho10": "매도호가10",
        "bidho10": "매수호가10",
        "offerrem10": "매도호가잔량10",
        "bidrem10": "매수호가잔량10",
        "totofferrem": "총매도호가잔량",
        "totbidrem": "총매수호가잔량",
        "donsigubun": "동시호가구분",
        "alloc_gubun": "배분적용구분",
        "volume": "누적거래량",
    },


# KOSDAQ호가잔량
    "HA_":{
        "shcode": "단축코드",
        "hotime": "호가시간",
        "offerho1": "매도호가1",
        "bidho1": "매수호가1",
        "offerrem1": "매도호가잔량1",
        "bidrem1": "매수호가잔량1",
        "offerho2": "매도호가2",
        "bidho2": "매수호가2",
        "offerrem2": "매도호가잔량2",
        "bidrem2": "매수호가잔량2",
        "offerho3": "매도호가3",
        "bidho3": "매수호가3",
        "offerrem3": "매도호가잔량3",
        "bidrem3": "매수호가잔량3",
        "offerho4": "매도호가4",
        "bidho4": "매수호가4",
        "offerrem4": "매도호가잔량4",
        "bidrem4": "매수호가잔량4",
        "offerho5": "매도호가5",
        "bidho5": "매수호가5",
        "offerrem5": "매도호가잔량5",
        "bidrem5": "매수호가잔량5",
        "offerho6": "매도호가6",
        "bidho6": "매수호가6",
        "offerrem6": "매도호가잔량6",
        "bidrem6": "매수호가잔량6",
        "offerho7": "매도호가7",
        "bidho7": "매수호가7",
        "offerrem7": "매도호가잔량7",
        "bidrem7": "매수호가잔량7",
        "offerho8": "매도호가8",
        "bidho8": "매수호가8",
        "offerrem8": "매도호가잔량8",
        "bidrem8": "매수호가잔량8",
        "offerho9": "매도호가9",
        "bidho9": "매수호가9",
        "offerrem9": "매도호가잔량9",
        "bidrem9": "매수호가잔량9",
        "offerho10": "매도호가10",
        "bidho10": "매수호가10",
        "offerrem10": "매도호가잔량10",
        "bidrem10": "매수호가잔량10",
        "totofferrem": "총매도호가잔량",
        "totbidrem": "총매수호가잔량",
        "donsigubun": "동시호가구분",
        "alloc_gubun": "배분적용구분",
        "volume": "누적거래량",
    },
    
    # KOSDAQ체결
    "K3_": {
        "shcode": "단축코드",
        "chetime": "체결시간",
        "sign": "전일대비구분",
        "change": "전일대비",
        "drate": "등락율",
        "price": "현재가",
        "opentime": "시가시간",
        "open": "시가",
        "hightime": "고가시간",
        "high": "고가",
        "lowtime": "저가시간",
        "low": "저가",
        "cgubun": "체결구분",
        "cvolume": "체결량",
        "volume": "누적거래량",
        "value": "누적거래대금",
        "mdvolume": "매도누적체결량",
        "mdchecnt": "매도누적체결건수",
        "msvolume": "매수누적체결량",
        "mschecnt": "매수누적체결건수",
        "cpower": "체결강도",
        "w_avrg": "가중평균가",
        "offerho": "매도호가",
        "bidho": "매수호가",
        "status": "장정보",
        "jnilvolume": "전일동시간대거래량",
    },
    
    # KOSPI체결
    "S3_": {
        "shcode": "단축코드",
        "chetime": "체결시간",
        "sign": "전일대비구분",
        "change": "전일대비",
        "drate": "등락율",
        "price": "현재가",
        "opentime": "시가시간",
        "open": "시가",
        "hightime": "고가시간",
        "high": "고가",
        "lowtime": "저가시간",
        "low": "저가",
        "cgubun": "체결구분",
        "cvolume": "체결량",
        "volume": "누적거래량",
        "value": "누적거래대금",
        "mdvolume": "매도누적체결량",
        "mdchecnt": "매도누적체결건수",
        "msvolume": "매수누적체결량",
        "mschecnt": "매수누적체결건수",
        "cpower": "체결강도",
        "w_avrg": "가중평균가",
        "offerho": "매도호가",
        "bidho": "매수호가",
        "status": "장정보",
        "jnilvolume": "전일동시간대거래량",
    },
    "NWS":{
        "date": "날짜",
        "time": "시간",
        "id": "뉴스구분자",
        "realkey": "키값",
        "title": "제목",
        "code": "단축종목코드",
        "bodysize": "BODY길이",
    },
}